### ISSUE TITLE
Fix twitter share intent

### ISSUE THREAD

**Issue by sasicodes** [lenstube-xyz/lenstube#218] opened 2022-10-19 04:48 UTC
This post title text is not accepting in intent

https://twitter.com/intent/tweet?url=https://lenstube.xyz/watch/0x014d21-0x04&text=Stray%20-%20Part%201%20|%20THE%20MOST%20PERFECT%20GAME&via=lenstubexyz&related=Lenstube&hashtags=Lenstube

<img width="1204" alt="image" src="https://user-images.githubusercontent.com/29498872/196600146-1e0ff30c-d0e5-4353-b9b9-4d0f07d9c23f.png">

**Comment by zt4ff** [comment] 2022-10-23 14:36
<img width="574" alt="Screen Shot 2022-10-23 at 3 34 52 PM" src="https://user-images.githubusercontent.com/61902277/197398108-b9c3fb44-7543-4df8-b08a-664a8d2e6f39.png">

@sasicodes 
I think it's accepting from the screenshot I sent

If not, can you assign it to me and explain further please?

**Comment by sasicodes** [comment] 2022-10-23 15:01
weird 🤔 I think it's not working for me

Browser - Brave

**Comment by RamK777-stack** [comment] 2022-10-23 15:50
I able to reproduce and found the root cause for this issue. WIP. Can I assign to myself @sasicodes ?

**Comment by sasicodes** [comment] 2022-10-23 15:57
@RamK777-stack 👍🏻

**Closed** 2022-10-25 06:07 UTC
Labels: hacktoberfest
